import React,{useEffect,useState} from 'react';
import {api} from '../../api'; import {KeyRound,PlugZap,ShieldCheck,Server,Save,RefreshCw} from 'lucide-react'; import {useApp} from '../../context/AppContext'; import {LiquidGlass} from '../common/LiquidGlass';
type Config={provider:string;protocol:string;baseUrl:string;model:string;credentialConfigured?:boolean;presets?:Record<string,any>};
export const AiProviderSettings:React.FC=()=>{const {language,showToast}=useApp();const [cfg,setCfg]=useState<Config>({provider:'offline',protocol:'offline',baseUrl:'',model:'local-rules'});const [key,setKey]=useState('');const [busy,setBusy]=useState(false);
 const load=()=>api('/api/ai/config').then(setCfg).catch(e=>showToast('error','AI config',e.message));useEffect(()=>{ void load(); },[]);
 const choose=(p:string)=>{const x=cfg.presets?.[p]||{};setCfg({...cfg,provider:p,protocol:x.protocol||'openai',baseUrl:x.baseUrl||'',model:x.model||''})};
 const save=async()=>{setBusy(true);try{const x=await api('/api/ai/config',{method:'POST',body:JSON.stringify({...cfg,apiKey:key})});setCfg(x);setKey('');showToast('success',language==='zh'?'AI 配置已安全保存':'AI configuration saved',x.provider)}catch(e:any){showToast('error','AI config',e.message)}finally{setBusy(false)}};
 const test=async()=>{setBusy(true);try{const x=await api('/api/ai/test',{method:'POST',body:'{}'});showToast('success',language==='zh'?'连接测试成功':'Connection test passed',x.reply)}catch(e:any){showToast('error',language==='zh'?'测试失败':'Test failed',e.message)}finally{setBusy(false)}};
 return <LiquidGlass variant="panel" glowColor="cyan" className="p-5 space-y-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-2xl bg-cyan-500/15 border border-cyan-400/30 flex items-center justify-center"><PlugZap className="w-5 h-5 text-cyan-400"/></div><div><h3 className="font-bold text-slate-900 dark:text-white">{language==='zh'?'AI API 提供商与自定义接口':'AI Provider & Custom API'}</h3><p className="text-xs text-slate-500">{language==='zh'?'密钥只发送到服务器并以 root 0600 文件保存，不保存在浏览器。':'Keys are sent to the server and stored in a root-only 0600 file, never in browser storage.'}</p></div></div><span className="text-xs px-2 py-1 rounded-full bg-emerald-500/10 text-emerald-500 border border-emerald-500/20">{cfg.credentialConfigured?'KEY SET':'NO KEY'}</span></div>
 <div className="grid grid-cols-2 md:grid-cols-6 gap-2">{['offline','gemini','groq','openrouter','mistral','cerebras','custom'].map(p=><button key={p} onClick={()=>choose(p)} className={`px-3 py-2 rounded-xl text-xs border ${cfg.provider===p?'bg-cyan-400 text-slate-950 border-cyan-300':'bg-white/40 dark:bg-slate-950/40 border-slate-300/40 dark:border-white/10'}`}>{p.toUpperCase()}</button>)}</div>
 <div className="grid md:grid-cols-2 gap-3"><label className="text-xs space-y-1"><span>Protocol</span><select value={cfg.protocol} onChange={e=>setCfg({...cfg,protocol:e.target.value})} className="w-full h-10 px-3 rounded-xl bg-white/80 dark:bg-slate-950/80 border border-slate-300/50 dark:border-white/10"><option value="offline">Offline rules</option><option value="openai">OpenAI compatible</option><option value="gemini">Gemini REST</option></select></label><label className="text-xs space-y-1"><span>Model ID</span><input value={cfg.model} onChange={e=>setCfg({...cfg,model:e.target.value})} className="w-full h-10 px-3 rounded-xl bg-white/80 dark:bg-slate-950/80 border border-slate-300/50 dark:border-white/10"/></label><label className="text-xs space-y-1 md:col-span-2"><span>Base URL</span><input value={cfg.baseUrl} onChange={e=>setCfg({...cfg,baseUrl:e.target.value})} placeholder="https://api.example.com/v1" className="w-full h-10 px-3 rounded-xl font-mono bg-white/80 dark:bg-slate-950/80 border border-slate-300/50 dark:border-white/10"/></label><label className="text-xs space-y-1 md:col-span-2"><span>{language==='zh'?'API 密钥，留空则保留现有密钥':'API key, leave blank to keep existing key'}</span><input type="password" value={key} onChange={e=>setKey(e.target.value)} autoComplete="new-password" className="w-full h-10 px-3 rounded-xl font-mono bg-white/80 dark:bg-slate-950/80 border border-slate-300/50 dark:border-white/10"/></label></div>
 <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/20 text-xs text-amber-700 dark:text-amber-300 flex gap-2"><ShieldCheck className="w-4 h-4 shrink-0"/><span>{language==='zh'?'自定义接口仅允许公网 HTTPS 地址，后端阻止 localhost、内网和保留地址，避免 SSRF。免费额度和数据政策由提供商决定，请自行核对。':'Custom endpoints must use public HTTPS. Local, private, and reserved targets are blocked to reduce SSRF risk. Provider quotas and data policies remain provider-controlled.'}</span></div>
 <div className="flex justify-end gap-2"><button disabled={busy} onClick={test} className="px-4 py-2 rounded-xl border border-cyan-500/30 text-cyan-500 flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${busy?'animate-spin':''}`}/>{language==='zh'?'测试':'Test'}</button><button disabled={busy} onClick={save} className="px-4 py-2 rounded-xl bg-cyan-400 text-slate-950 font-bold flex items-center gap-2"><Save className="w-4 h-4"/>{language==='zh'?'安全保存':'Save securely'}</button></div></LiquidGlass>};
