import express from 'express'; import path from 'path'; import fs from 'fs'; import crypto from 'crypto'; import {spawn} from 'child_process';
const app=express(), PORT=Number(process.env.PORT||8787), HOST=process.env.HOST||'127.0.0.1', DIST=process.env.DIST_DIR||path.join(process.cwd(),'dist');
app.disable('x-powered-by'); app.set('trust proxy','loopback'); app.use(express.json({limit:'256kb'}));
const ADMIN_FILE=process.env.ADMIN_FILE||'/etc/mailstack/admin.json'; const sessions=new Map<string,{expires:number,csrf:string,user:string}>();
function credentials(){try{return JSON.parse(fs.readFileSync(ADMIN_FILE,'utf8'))}catch{return null}}
function verify(user:string,password:string){const c=credentials();if(!c||user!==c.username||c.algorithm!=='pbkdf2-sha256')return false;const got=crypto.pbkdf2Sync(password,Buffer.from(c.salt,'hex'),Number(c.iterations),32,'sha256'),expected=Buffer.from(c.hash,'hex');return got.length===expected.length&&crypto.timingSafeEqual(got,expected)}
function cookies(req:any){return Object.fromEntries(String(req.headers.cookie||'').split(';').map((x:string)=>x.trim().split(/=(.*)/s)).filter((x:any)=>x[0]))}
function auth(req:any,res:any,next:any){const sid=cookies(req).mailstack_session,s=sessions.get(sid);if(!s||s.expires<Date.now())return res.status(401).json({error:'AUTH_REQUIRED'});if(!['GET','HEAD'].includes(req.method)&&req.headers['x-csrf-token']!==s.csrf)return res.status(403).json({error:'CSRF_INVALID'});req.session=s;next()}
function ctl(action:string,data:any={}){return new Promise<any>((resolve,reject)=>{const p=spawn('sudo',['/opt/mailstack/backend/mailstackctl.py'],{stdio:['pipe','pipe','pipe']});let o='',e='';p.stdout.on('data',d=>o+=d);p.stderr.on('data',d=>e+=d);p.on('close',c=>{try{const j=JSON.parse(o);j.ok?resolve(j.data):reject(new Error(j.error))}catch{reject(new Error(e||'helper failed '+c))}});p.stdin.end(JSON.stringify({action,data}))})}
const attempts=new Map<string,{count:number,until:number}>();
app.post('/api/auth/login',(req,res)=>{const ip=req.ip||'unknown',a=attempts.get(ip);if(a&&a.until>Date.now())return res.status(429).json({error:'TOO_MANY_ATTEMPTS'});const user=String(req.body?.username||''),password=String(req.body?.password||'');if(!verify(user,password)){const count=(a?.count||0)+1;attempts.set(ip,{count,until:count>=5?Date.now()+300000:0});return res.status(401).json({error:'INVALID_CREDENTIALS'})}attempts.delete(ip);const sid=crypto.randomBytes(32).toString('hex'),csrf=crypto.randomBytes(24).toString('hex');sessions.set(sid,{expires:Date.now()+8*3600e3,csrf,user});res.setHeader('Set-Cookie',`mailstack_session=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${req.secure?'; Secure':''}`);res.json({ok:true,csrf,username:user})});
app.post('/api/auth/logout',auth,(req,res)=>{sessions.delete(cookies(req).mailstack_session);res.setHeader('Set-Cookie','mailstack_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/auth/session',auth,(req:any,res)=>res.json({ok:true,csrf:req.session.csrf,username:req.session.user}));
app.get('/api/health',(_q,res)=>res.json({status:'ok',time:new Date().toISOString()}));app.use('/api',auth);
const get=(url:string,action:string)=>app.get(url,async(_q,res)=>{try{res.json(await ctl(action))}catch(e:any){res.status(500).json({error:'OP_FAILED',message:e.message})}});
const post=(url:string,action:string)=>app.post(url,async(req,res)=>{try{res.json(await ctl(action,req.body))}catch(e:any){res.status(422).json({error:'OP_FAILED',message:e.message})}});
get('/api/snapshot','snapshot');get('/api/domains','domains.list');post('/api/domains','domains.add');app.delete('/api/domains/:id',async(req,res)=>{try{res.json(await ctl('domains.delete',{id:req.params.id}))}catch(e:any){res.status(422).json({message:e.message})}});
post('/api/users','users.add');app.delete('/api/users/:id',async(req,res)=>{try{res.json(await ctl('users.delete',{id:req.params.id}))}catch(e:any){res.status(422).json({message:e.message})}});
post('/api/aliases','aliases.add');app.delete('/api/aliases/:id',async(req,res)=>{try{res.json(await ctl('aliases.delete',{id:req.params.id}))}catch(e:any){res.status(422).json({message:e.message})}});
post('/api/services/action','services.action');post('/api/queue/action','queue.action');get('/api/logs','logs.list');post('/api/security/scan','security.scan');get('/api/certificates','certs.list');post('/api/certificates/renew','certs.renew');
get('/api/admin','admin.get');app.post('/api/admin',async(req,res)=>{try{const result=await ctl('admin.set',req.body);sessions.clear();res.setHeader('Set-Cookie','mailstack_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({...result,reauthenticate:true})}catch(e:any){res.status(422).json({error:'OP_FAILED',message:e.message})}});
get('/api/ai/config','ai.config.get');post('/api/ai/config','ai.config.set');post('/api/ai/test','ai.test');post('/api/ai/dns-chat','ai.chat');post('/api/ai/diagnose-dns','ai.diagnose');post('/api/ai/parse-dns-raw','ai.parse');
app.use(express.static(DIST,{index:false,maxAge:'1h'}));app.get('*',(_q,res)=>res.sendFile(path.join(DIST,'index.html')));app.listen(PORT,HOST,()=>console.log(`MailStack API on ${HOST}:${PORT}`));
